version: "3.1"  # Adjust version if needed
services:
  mysql_db:
    image: mysql:8.0
    volumes:
      - mydata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: irohas2004
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8085:80
    environment:
      - PMA_HOST=mysql_db
    depends_on:
      - mysql_db
volumes:
  mydata:
  uploadsImage: