package com.example.ecommerce.domain.entities.product;
public enum EntityAction {
    UPDATE_PRODUCT,CREATE_PRODUCT,DELETE_PRODUCT,
    UPDATE_INVENTORY, DELETE_QUANTITY, CREATE_INVENTORY,
    CREATE_ACCOUNT, DELETE_AACCOUNT, UPDATE_ACCOUNT,
    CREATE_VENDOR, UPDATE_VENDOR, DELETE_VENDOR, LOCK_ACCOUNT,
    CREATE_FILE, DELETE_FILE,
    CREATE_EVALUATION, DELETE_EVALUATION, UPDATE_EVALUATION,
    CREATE_CATE, DELETE_CATE, UPDATE_CATE,
    CTEATE_BRAND, DELETE_BRAND, UPDATE_BRAND,
    CREATE_ORDER, DELETE_ORDER
}
